### ISSUE TITLE
Extend different languages 

### ISSUE THREAD

**Issue by dxcore35** [jwilk/ydpy#1]
I would like to extend support for different languages, what is that integer number represent?

`DICTIONARIES = (
    ('e', 'en-pl', 'English-Polish', 100),
    ('p', 'pl-en', 'Polish-English', 101),
    ('g', 'de-pl', 'German-Polish', 200),
    ('o', 'pl-de', 'Polish-German', 201),
)`

**Comment by jwilk** [comment]
It's the number included in names of the data files.
For example, the English-Polish dictionary consists of these files:
```
dict100.dat
dict100.idx
```

**Comment by jwilk** [comment]
(But I don't believe any other dictionaries have ever been made in the format that libydpdict handles.)

**Comment by dxcore35** [comment]
OK so you are using offline data instead of connecting to websites right? 

How did you manage to get these data? ☺️

---
Denis

**Comment by jwilk** [comment]
> I don't believe any other dictionaries have ever been made in the format that libydpdict handles.

I'm closing this bug based on this premise.
