### ISSUE TITLE
Data source information

### ISSUE THREAD

**Issue by dxcore35** [jwilk/ydpy#2]
I wrote you are using data from https://www.collinsdictionary.com, but I cannot find there Polish language. From where the data are coming from? 

Thanks

**Comment by jwilk** [comment]
README links to the YDP homepage, where you used to be able to purchase the dictionaries.
But apparently in the mean time the company was shut down or something…

I've updated README: 407b92117e77c76e1a706fddc9f24393986a16a2, 43f80a35f154825e31188ee08d94aaca9a4f47b9
Is it now clear for you?

**Comment by dxcore35** [comment]
Yes, now it is clear! But how you are handling the copyright for data? Because you define MIT licence...

**Comment by jwilk** [comment]
> But how you are handling the copyright for data?

I don't hold copyright for the data.

> Because you define MIT licence...

The license applies to the code in this repository (and in the release tarballs).
It doesn't apply to anything else.

**Comment by jwilk** [comment]
I've just released ydpy 0.4.1, which includes the updated README.
